# Web服务配置
server:
  # 端口
  port: 10086

# Spring配置
spring:
  # 数据源配置
  datasource:
    # 用户名
    username: root
    # 密码
    password: root

# 日志配置
logging:
  # 显示级别
  level:
    cn.maplerabbit.rlg: trace

# debug开关
debug: false

# knife4j配置
knife4j:
  # 开关
  enable: true

# 项目全局配置
rlg:
  # 文件系统相关配置
  file:
    # 根目录
    root: D:\Projects\MapleProjects\RedLeafGarden\TestFile
  # uuid配置
  uuid:
    # UUID容器最大容量
    max: 100