# Web服务端口
server:
  port: 10086

# 连接数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rlg_rms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Chongqing
    username: root
    password: root

# 日志的显示级别
logging:
  level:
    cn.maplerabbit.rlg: trace

# debug开关
debug: false

# knife4j配置
knife4j:
  # 开关
  enable: true

# 项目配置
rlg:
  # 文件系统相关配置
  file:
    # 配置根目录
    root: D:\Projects\MapleProjects\RedLeafGarden\TestFile
  uuid:
    # UUID容器最大容量
    max: 100