# Web服务端口
server:
  port: 8080

# 连接数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rlg_rms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Chongqing
    username: root
    password: root

# 日志的显示级别
logging:
  level:
    cn.maplerabbit.rlg: trace

# debug开关
debug: false