# ============ #
#  本地环境配置  #
# ============ #

# debug开关
debug: false

# Web服务配置
server:
  # 端口
  port: 10086

# Spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/rlg_rms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Chongqing
    username: root
    password: root
  # servlet配置
  servlet:
    # multipart文件传输配置
    multipart:
      # 单文件大小上限
      max-file-size: 10MB
      # 单次请求文件总大小上限
      max-request-size: 100MB
  # 配置系统邮箱账户
  mail:
    host: smtp.qq.com
    username: schuke@foxmail.com
    password: lkwydyooqanydihb
    properties:
      mail.smtp.timeout: 60000
  jackson:
    time-zone: GMT+8

# 日志配置
logging:
  # 显示级别
  level:
    cn.maplerabbit.rlg: trace

# 项目全局配置
rlg:
  # 文件系统相关配置
  file:
    # 文件根目录
    root: D:/rlg
  # JWT相关配置
  jwt:
    secretKey: RedLeafGarden-JsonWebToken-SecretKey
    # JWT的有效时长（单位分钟）：一星期
    usableMinutes: 10080