# ============ #
#  开发环境配置  #
# ============ #

# debug开关
debug: false

# Web服务配置
server:
  # 端口
  port: 10086

# Spring配置
spring:
  # 配置系统邮箱账户
  mail:
    host: smtp.qq.com
    username: schuke@foxmail.com
    password: lkwydyooqanydihb
    properties:
      mail.smtp.timeout: 60000
  # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/rlg_rms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Chongqing

# 日志配置
logging:
  # 显示级别
  level:
    cn.maplerabbit.rlg: trace

# knife4j配置
knife4j:
  # 开关
  enable: true

# 项目全局配置
rlg:
  # 文件系统相关配置
  file:
    # 文件根目录
    root-location: D:/rlg