# ============ #
#  生产环境配置  #
# ============ #

# debug开关
debug: false

# Web服务配置
server:
  # 端口
  port: 10086

# Spring配置
spring:
  # 数据源配置
  datasource:
    # 用户名
    username: root
    # 密码
    password: root

# 日志配置
logging:
  # 显示级别
  level:
    cn.maplerabbit.rlg: info

# knife4j配置
knife4j:
  # 开关
  enable: false

# 项目全局配置
rlg:
  # 文件系统相关配置
  file:
    directory:
      # 系统静态目录
      static: D:/rlg/static
      # 用户文件根目录
      user: D:/rlg/user