# Spring配置
spring:
  main:
    # 关闭banner
    banner-mode: off
  # Profile相关配置
  profiles:
    # 激活指定名称的Profile配置
    active: dev

# MyBatis配置
mybatis:
  # 配置SQL语句的XML文件的位置，classpath后面加上*才能扫描到所有模块
  mapper-locations: classpath*:mapper/*.xml

# 日志配置
logging:
  level:
    root: warn

# knife4j配置
knife4j:
  setting:
    language: zh-CN