# ============ #
#  配置文件主体  #
# ============ #

# Spring配置
spring:
  # Profile相关配置
  profiles:
    # 激活指定名称的Profile配置
    active: local
  # 邮箱配置
  mail:
    protocol: smtp
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # web配置
  web:
    # 静态资源配置
    resources:
      # 静态资源根路径
      static-locations:
        - classpath:static
        - file:/${rlg.file.root-location}/static
  mvc:
    static-path-pattern: /static/**

# MyBatis配置
mybatis:
  # Mapper.xml文件位置
  mapper-locations: classpath*:mapper/*.xml

# 日志配置
logging:
  # 显示级别
  level:
    root: info

# knife4j配置
knife4j:
  setting:
    language: zh-CN

# 项目全局配置
rlg:
  # 文件系统相关配置
  file:
    store: ${rlg.file.root-location}/store