# ============ #
#  配置文件主体  #
# ============ #

# Spring配置
spring:
  # Profile相关配置
  profiles:
    # 激活指定名称的Profile配置
    active: local
  # 配置validation资源信息
  messages:
    # 国际化资源文件名
    basename: validator
    encoding: UTF-8
    cache-duration: 60
    always-use-message-format: true
  # servlet配置
  servlet:
    # multipart文件传输配置
    multipart:
      # 单文件大小上限
      max-file-size: 10MB
      # 单次请求文件总大小上限
      max-request-size: 100MB
      # multipart文件传输配置
      enabled: true
      # 文件写入磁盘的阈值，超过这个大小的文件会被存储为临时文件
      file-size-threshold: 10MB
  # 邮箱配置
  mail:
    properties:
      mail.smtp.timeout: 60000
    protocol: smtp
  # 数据源配置
  datasource:
    # 数据源驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  # web配置
  web:
    # 静态资源配置
    resources:
      # 静态资源根路径
      static-locations:
      - classpath:static
      - file:/${rlg.file.rootDir}/static
  # spring mvc配置
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    time-zone: GMT+8
  # security配置
  security:
    urlAllowList:
      - /user/email-login
      - /user/login
      - /user/register
      - /doc.html
      - /**/*.css
      - /**/*.js
      - /favicon.ico
      - /swagger-resources
      - /v2/api-docs

# Web服务配置
server:
  servlet:
    encoding:
      charset: UTF-8

# MyBatis配置
mybatis:
  configuration:
    # 下划线与驼峰命名法映射
    map-underscore-to-camel-case: true
  # Mapper.xml文件位置
  mapper-locations: classpath*:mapper/*.xml

# 日志配置
logging:
  # 显示级别
  level:
    root: info

# knife4j配置
knife4j:
  setting:
    language: zh-CN

# 项目全局配置
rlg:
  # 验证码配置
  code:
    # 有效时间（单位分钟）
    usableTime: 15
  # 文件目录配置
  directory:
    # 静态资源路径
    staticDir: ${rlg.file.rootDir}/static
    # 用户文件仓库路径
    storeDir: ${rlg.file.rootDir}/store
  # JWT相关配置
  jwt:
    # jwt签名算法
    algorithm: HS256
    # jwt类型
    type: JWT
    # 密钥
    secretKey: RedLeafGarden-JsonWebToken-SecretKey
    # JWT的有效时长（单位分钟）：一星期
    usableMinutes: 10080
    # 长度下限
    minLength: 105
    # 存放jwt的请求头名称
    header: Authorization