# ============ #
#  配置文件主体  #
# ============ #

# Web服务配置
server:
  # 端口
  port: 80
  servlet:
    encoding:
      charset: UTF-8

# Spring配置
spring:
  # Profile相关配置
  profiles:
    include:
      - rlg
    # 激活指定名称的Profile配置
    active: local
  # 配置validation资源信息
  messages:
    # 国际化资源文件名
    basename: validator
    encoding: UTF-8
    cache-duration: 60
    always-use-message-format: true
  # servlet配置
  servlet:
    # multipart文件传输配置
    multipart:
      # 单文件大小上限
      max-file-size: 10MB
      # 单次请求文件总大小上限
      max-request-size: 100MB
      # multipart文件传输配置
      enabled: true
      # 文件写入磁盘的阈值，超过这个大小的文件会被存储为临时文件
      file-size-threshold: 10MB
  # 邮箱配置
  mail:
    properties:
      mail.smtp.timeout: 60000
    protocol: smtp
  # 数据源配置
  datasource:
    # 数据源驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
  # web配置
  web:
    # 静态资源配置
    resources:
      # 静态资源根路径
      static-locations:
      - classpath:static
      - file:${rlg.directory.root-dir}
  # spring mvc配置
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    time-zone: GMT+8

# MyBatis配置
mybatis:
  configuration:
    # 下划线与驼峰命名法映射
    map-underscore-to-camel-case: true
  # Mapper.xml文件位置
  mapper-locations: classpath*:mapper/*.xml

# 日志配置
logging:
  # 日志文件配置
  file:
    # 文件路径
    path: ${rlg.directory.log-dir}/sys_log
  # 显示级别
  level:
    root: info
    cn.maplerabbit.rlg: info
