# ============ #
#  项目全局配置  #
# ============ #

rlg:
  # 文件模块配置
  file:
    # 根目录路径
    root-dir: C:/rlg
    # ftp配置
    ftp:
      # 主机地址
      host: 127.0.0.1
      # 用户名
      username: rlgroot
      # 密码
      password: P@ssw0rdRoot