# ============ #
#  生产环境配置  #
# ============ #

# Spring配置
spring:
  # 数据源配置
  datasource:
    url:
    username:
    password:
  # 配置系统邮箱账户
  mail:
    host:
    username:
    password:

rlg:
  # 文件目录配置
  file:
    # 根目录路径
    root-dir:
    # ftp配置
    ftp:
      # 主机地址
      host:
      # 用户名
      username:
      # 密码
      password: